import type { Metadata } from 'next'
import { Merriweather } from 'next/font/google'
import './globals.css'

const font = Merriweather({ subsets: ['latin'], display: 'swap',weight: ['400', '700'], })

export const metadata: Metadata = {
  title: 'Labor and Work Duration Estimation Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
